### PR TITLE
gs fixes

### PR DESCRIPTION
**Pull request by azazellochg**
- update readme
- add client that uses requests
- use executable = test class name
- separate saving and uploading
- remove codespeed-client dep

### CODE REVIEW

**Comment by pconesa** [comment]
Are you using this?

**Comment by azazellochg** [comment]
yes, I tested it.

**Comment by azazellochg** [comment]
dont know what happened with http://scipion-test.cnb.csic.es:8000/comparison/

**Comment by pconesa** [comment]
we changed the machine and never install that server back. Something todo

**Review by pconesa — APPROVED** [review]

**Pull request merged**
